### ISSUE TITLE
Running linear models requires nn dependencies

### ISSUE THREAD

**Issue by Sinacam** [ASUS-AICS/LibMultiLabel#270]
`main.py` uses `libmultilabel/logging.py` which unconditionally imports `transformers`.
This makes it impossible to run linear models without installing `transformers`.

Also, `stream_handler` in `main.py` is never used
https://github.com/ASUS-AICS/LibMultiLabel/blob/c5103b41a3dc5e2301aa9619c50ad5cce9b054dc/main.py#L195

**Comment by Eleven1Liu** [comment]
@sammer1107 help

**Comment by Eleven1Liu** [comment]
resolved by #273
