### ISSUE TITLE
Linear in eval mode does not have multiclass

### ISSUE THREAD

**Issue by Sinacam** [ASUS-AICS/LibMultiLabel#271]
`config.multiclass` is only set in the else branch
https://github.com/ASUS-AICS/LibMultiLabel/blob/c5103b41a3dc5e2301aa9619c50ad5cce9b054dc/linear_trainer.py#L53-L66
Which is later used in `linear_test`
https://github.com/ASUS-AICS/LibMultiLabel/blob/c5103b41a3dc5e2301aa9619c50ad5cce9b054dc/linear_trainer.py#L12-L17
causing a missing attribute error.

As an addendum, I think `config` should never be modified after `main.py`. This was a huge source of confusion on the nn side previously.

**Comment by Eleven1Liu** [comment]
Resolved by PR #284
