### ISSUE TITLE
Maybe let "evaluate()" take the output of model instead of model is a better and more general choice.

### ISSUE THREAD

**Issue by yxliu-ntu** [ASUS-AICS/LibMultiLabel#41]
https://github.com/ASUS-AICS/LibMultiLabel/blob/bbc31f578810f23827a8b1362792d938dcaa16b7/libmultilabel/evaluate.py#L11-L31

**Comment by Eleven1Liu** [comment]
Hi @yxliu-ntu,

Sure. We will add this as a long term goal, thanks! :)

**Comment by cjlin1** [comment]
now this evaluate supports an incremental setting to accumulate 
predicted results by batches. SO the changes are not as easy as we 
thought before... So this isn't a quick change and need some re-design

**Comment by yxliu-ntu** [comment]
Let evaluation metrics support a sparse output matrix might help.
