### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by yxliu-ntu** [ASUS-AICS/LibMultiLabel#42]
- Why train_step() check if isinstance(outputs, dict) is True  but predict() does not?
https://github.com/ASUS-AICS/LibMultiLabel/blob/bbc31f578810f23827a8b1362792d938dcaa16b7/libmultilabel/model.py#L177

- The output size should be "(batch_size, num_filter, length - kernel_szie + 1)".
https://github.com/ASUS-AICS/LibMultiLabel/blob/19728f8b7a356039196ede20c7984bc0818c1596/libmultilabel/networks/kim_cnn.py#L35

- It might be weird to set the activation function for some customized model inheriting from this basic class here.
https://github.com/ASUS-AICS/LibMultiLabel/blob/19728f8b7a356039196ede20c7984bc0818c1596/libmultilabel/networks/base.py#L19

**Comment by cjlin1** [comment]
first two solved. the third is about how to let users input network configuration. it's a general issue that won't be handled soon
