### ISSUE TITLE
Specifying behaviour when text has tabs

### ISSUE THREAD

**Issue by Sinacam** [ASUS-AICS/LibMultiLabel#64]
When running on Wiki10-31K from [libsvm datasets][1], I encountered problems with having stray `\t` in the text.
Specifically, the first occurrence is at line 322, where the text after the first `\t` is cut off.
The readme should (currently) be explicit that `\t` is forbidden in the text.

On the other hand, the data loading should either handle such situations or emit an error, not run silently and erroneously.
There are two situations:
* If there is two `\t` in a line, there is ambiguity due to permitting an optional id column. Perhaps require the entire file to have the same column count.
* If there is three or more `\t` in a line, every `\t` after the second shouldn't be treated as a separator, it is either part of the text or an error.

The relevant code is
https://github.com/ASUS-AICS/LibMultiLabel/blob/260850c3d69bd9e35b0e5198c6af901b88903a49/libmultilabel/data_utils.py#L80-L82

[1]: https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multilabel.html#Wiki10-31K

**Comment by sian-chen** [comment]
Thank you for raising the issue.
We modified the behavior in PR #71 as follows:
1. Check the first file. Raise an error if not 2 or 3 columns.
2. Raise a warning with line number and skip the line if encounter any unexpected field (more \t than the first line).

We also update the README to describe this behavior explicitly.
