### ISSUE TITLE
Lack of license information

### ISSUE THREAD

**Issue by szlin** [ASUS-AICS/LibMultiLabel#65]
Hi,

After checking the content of the repository, I didn't find an explicitly specific open source license declaration here.

It would be essential to tag an explicit open source license if you want to outreach your work as an open source project, as shown below.

> "Can I call my program "Open Source" even if I don't use an approved license?
> Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people. This is not merely a theoretical concern — we have seen this confusion happen in the past, and it's part of the reason we have a formal license approval process. See also our page on license proliferation for why this is a problem." [1]

[1] https://opensource.org/faq#avoid-unapproved-licenses

It would be great if you can add the license information in SPDX format.

Just my two cents.

SZ

**Comment by Eleven1Liu** [comment]
Hi @szlin,

Thanks for the feedback and spending time checking the repo. We have added a MIT license here:
https://github.com/ASUS-AICS/LibMultiLabel/blob/master/LICENSE

If there's any suggestion, feel free to ping us.
Thanks!
