### ISSUE TITLE
how to generate vocab.csv and processed_full.embed in MIMIC-50?

### ISSUE THREAD

**Issue by Abhinav43** [ASUS-AICS/LibMultiLabel#81]
I was trying to run the MIMIC-50 examples and provided the data in the same format as specified. 
There are two extra files apart from training data files which are vocab.csv and processed_full.embed. 
There is no mention in docs or anywhere how to generate these files.

Kindly share the script or process on how to generate those files.
Also please specify what is difference between `Macro-F1` and `Another Macro-F1`?
Thank you!

**Comment by Eleven1Liu** [comment]
Hi @Abhinav43,

We use this script to generate `vocab.csv` and `processed_fulll.embed`. Please find them here: https://github.com/jamesmullenbach/caml-mimic/blob/master/notebooks/dataproc_mimic_III.ipynb .

For the difference of Macro-F1 and Another-Macro-F1, please see reference below for more details:
https://arxiv.org/pdf/1911.03347.pdf
https://www.csie.ntu.edu.tw/~cjlin/papers/parameter_selection/acl2021_parameter_selection.pdf

Happy coding! 😁
