### ISSUE TITLE
Question regarding adding own vocab and embeddings

### ISSUE THREAD

**Issue by Abhinav43** [ASUS-AICS/LibMultiLabel#83]
Hello developers, if I want to add my own embeddings such as Elmo or other so first I have to collect vocab for whole data for example :

if my data looks like this:

import numpy as np

```
sentences = [['this', 'is', 'the', 'first', 'sentence', 'for', 'emd'],
			       ['this', 'is', 'the', 'second', 'sentence'],
			       ['yet', 'another', 'sentence'],
			       ['one', 'more', 'sentence'],
			       ['and', 'the', 'final', 'sentence']]
```

I have created the vocab like this:

`vocab    = list(set([word for list_word in sentences for word in list_word]))`

And for example my elmo embedding matrix looks like this:

`embed    = np.random.uniform(-1,1,[len(vocab), 1024])`

Later I am transforming my embedding in .txt file such as:

```
team -0.17901678383350372 1.2405720949172974 ...
language 0.8667483925819397 5.001194953918457 ...
```

My question is do I need to add 'UNK' and 'PAD' etc in my vocab or my current code is fine?

**Comment by Eleven1Liu** [comment]
Hi @Abhinav43,

Elmo! sounds interesting!

(1) The format of `vocab_file` is like this:
```
team
language
```
After creating the vocab list, you should put all of the words line by line in a `vocab_file`.

(2) For the embedding of UNK and PAD
There's no need to add `UNK` and `PAD` to both `vocab_file` and `embed_file`.
The vectors of `PAD` and `UNK` default to a zero vector and random vector respectively.
